-- PostgreSQL schema. Every statement is IF NOT EXISTS so this file can be
-- applied on every boot; see ensureSchema.js.
--
-- Two deliberate carry-overs from the SQLite version, kept because changing
-- them would ripple all the way into the React code for no gain:
--   * money is `double precision`, not `numeric`. numeric is the correct type
--     for money in general, but the driver returns it as a string, and every
--     total in this app is arithmetic in JavaScript.
--   * is_active is a 0/1 smallint rather than a boolean, because the client
--     already compares it against 1 in several places.

-- Key/value app settings. Holds primary_currency, which every balance is
-- converted into for the household totals and charts.
CREATE TABLE IF NOT EXISTS settings (
  key   text PRIMARY KEY,
  value text NOT NULL
);

-- Who can sign in. Separate from `persons`: a person is whose money an account
-- holds, a user is someone who can open the app. They usually line up, but the
-- app never assumes it.
CREATE TABLE IF NOT EXISTS users (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username      text NOT NULL,
  password_hash text NOT NULL,
  created_at    timestamptz NOT NULL DEFAULT now()
);

-- SQLite had COLLATE NOCASE on the column; Postgres spells the same idea as a
-- unique index over the lowered value. Queries match on lower(username) to suit.
CREATE UNIQUE INDEX IF NOT EXISTS idx_users_username_lower ON users (lower(username));

-- The token is the credential — it's random and stored as-is, so there is no
-- signing secret to manage or leak. Deleting a row logs that session out.
CREATE TABLE IF NOT EXISTS sessions (
  token      text PRIMARY KEY,
  user_id    integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz NOT NULL
);

CREATE TABLE IF NOT EXISTS persons (
  id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- Free-form accounts: any number per person, each in its own currency.
-- `type` drives how a balance is read: 'savings' is reported separately,
-- and 'credit' is a card, where a negative balance is money owed rather
-- than an overdraft, so it subtracts from net worth and may go below zero.
CREATE TABLE IF NOT EXISTS accounts (
  id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  person_id       integer NOT NULL REFERENCES persons(id),
  name            text NOT NULL,
  currency        text NOT NULL DEFAULT 'AED',
  type            text NOT NULL DEFAULT 'current' CHECK (type IN ('current','savings','credit')),
  opening_balance double precision NOT NULL DEFAULT 0,
  is_active       smallint NOT NULL DEFAULT 1,
  sort_order      integer NOT NULL DEFAULT 0,
  created_at      timestamptz NOT NULL DEFAULT now()
);

-- Single ledger for every movement of money. `amount` is always positive;
-- `kind` carries the direction. A transfer is two rows sharing a transfer_id
-- (one transfer_out, one transfer_in), which lets the two legs hold different
-- amounts when the accounts are in different currencies.
CREATE TABLE IF NOT EXISTS transactions (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id  integer NOT NULL REFERENCES accounts(id),
  month       text NOT NULL,
  kind        text NOT NULL CHECK (kind IN ('income','expense','transfer_in','transfer_out')),
  amount      double precision NOT NULL,
  category    text,
  description text,
  transfer_id text,
  entry_date  text,
  created_at  timestamptz NOT NULL DEFAULT now()
);

-- Recurring charges. These are NOT written into `transactions`; they are
-- applied on the fly for every month in range, so editing or ending a
-- subscription immediately corrects past and future months alike.
CREATE TABLE IF NOT EXISTS subscriptions (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id    integer NOT NULL REFERENCES accounts(id),
  name          text NOT NULL,
  amount        double precision NOT NULL,
  cycle         text NOT NULL DEFAULT 'monthly' CHECK (cycle IN ('monthly','yearly')),
  billing_month integer,
  start_month   text NOT NULL,
  end_month     text,
  category      text,
  notes         text,
  is_active     smallint NOT NULL DEFAULT 1,
  created_at    timestamptz NOT NULL DEFAULT now()
);

-- fetched_at stays text: it holds an ISO string and is compared by its date
-- prefix to decide whether today's rate has already been fetched.
CREATE TABLE IF NOT EXISTS exchange_rates (
  base_currency   text NOT NULL,
  target_currency text NOT NULL,
  rate            double precision NOT NULL,
  fetched_at      text NOT NULL,
  PRIMARY KEY (base_currency, target_currency)
);

CREATE INDEX IF NOT EXISTS idx_sessions_user ON sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_accounts_person ON accounts(person_id);
CREATE INDEX IF NOT EXISTS idx_transactions_account_month ON transactions(account_id, month);
CREATE INDEX IF NOT EXISTS idx_transactions_month ON transactions(month);
CREATE INDEX IF NOT EXISTS idx_transactions_transfer ON transactions(transfer_id);
CREATE INDEX IF NOT EXISTS idx_subscriptions_account ON subscriptions(account_id);
