-- PostgreSQL schema. Every statement is IF NOT EXISTS so this file can be
-- applied on every boot; see ensureSchema.js.
--
-- Two deliberate carry-overs from the SQLite version, kept because changing
-- them would ripple all the way into the React code for no gain:
--   * money is `double precision`, not `numeric`. numeric is the correct type
--     for money in general, but the driver returns it as a string, and every
--     total in this app is arithmetic in JavaScript.
--   * is_active is a 0/1 smallint rather than a boolean, because the client
--     already compares it against 1 in several places.

-- Who can sign in. Separate from `persons`: a person is whose money an account
-- holds, a user is someone who can open the app. They usually line up, but the
-- app never assumes it.
CREATE TABLE IF NOT EXISTS users (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username      text NOT NULL,
  -- Optional, and nothing sends to it today. It is stored so that adding
  -- self-service password reset later is a contained change rather than a
  -- retrofit through signup and settings.
  email         text,
  password_hash text NOT NULL,
  -- Whether this person's amounts stay hidden until a passkey says otherwise.
  -- On the account rather than the device, so it follows you between them; each
  -- member of a household answers for themselves.
  --
  -- On by default, because the figures are the private part and a lock nobody
  -- switched on protects nobody. It is an intention rather than a state: with
  -- no passkey registered there is nothing to ask, so it lies dormant and the
  -- eye behaves as it always did. Adding a passkey is what wakes it.
  lock_amounts  boolean NOT NULL DEFAULT true,
  created_at    timestamptz NOT NULL DEFAULT now()
);

-- SQLite had COLLATE NOCASE on the column; Postgres spells the same idea as a
-- unique index over the lowered value. Queries match on lower(username) to suit.
CREATE UNIQUE INDEX IF NOT EXISTS idx_users_username_lower ON users (lower(username));
-- The index over email lives in migrations.js, not here. This file is applied
-- before migrations run, and CREATE TABLE IF NOT EXISTS does not add a column
-- to a table that already exists — so on any database that predates `email`,
-- indexing it here fails. The rule: an index belongs in migrations.js whenever
-- the column it covers was added by a migration.

-- The token is the credential — it's random and stored as-is, so there is no
-- signing secret to manage or leak. Deleting a row logs that session out.
CREATE TABLE IF NOT EXISTS sessions (
  token      text PRIMARY KEY,
  user_id    integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz NOT NULL
);

-- A household is one budget: its own people, accounts, ledger and settings.
-- Every user has at least one and may belong to several — their own, and any
-- they have been invited into. Nothing is shared between them.
CREATE TABLE IF NOT EXISTS households (
  id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- Who may open which household, and what they may do there.
--   owner    everything, including inviting people and deleting the household
--   editor   can record and change money
--   viewer   read-only
CREATE TABLE IF NOT EXISTS household_members (
  household_id integer NOT NULL REFERENCES households(id) ON DELETE CASCADE,
  user_id      integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  role         text NOT NULL DEFAULT 'editor' CHECK (role IN ('owner','editor','viewer')),
  created_at   timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (household_id, user_id)
);

-- An invitation is a random code handed over out of band. It carries the role
-- it will grant, so accepting one can never quietly give more access than the
-- owner intended, and it is single-use.
CREATE TABLE IF NOT EXISTS household_invites (
  code         text PRIMARY KEY,
  household_id integer NOT NULL REFERENCES households(id) ON DELETE CASCADE,
  role         text NOT NULL DEFAULT 'editor' CHECK (role IN ('owner','editor','viewer')),
  created_by   integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at   timestamptz NOT NULL DEFAULT now(),
  expires_at   timestamptz NOT NULL,
  accepted_by  integer REFERENCES users(id) ON DELETE SET NULL,
  accepted_at  timestamptz
);

-- Key/value settings, per household. Holds primary_currency, which every
-- balance in that household is converted into for its totals and charts.
CREATE TABLE IF NOT EXISTS settings (
  household_id integer NOT NULL REFERENCES households(id) ON DELETE CASCADE,
  key          text NOT NULL,
  value        text NOT NULL,
  PRIMARY KEY (household_id, key)
);

CREATE TABLE IF NOT EXISTS persons (
  id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  household_id integer NOT NULL REFERENCES households(id) ON DELETE CASCADE,
  name         text NOT NULL,
  created_at   timestamptz NOT NULL DEFAULT now()
);

-- Free-form accounts: any number per person, each in its own currency.
-- `type` drives how a balance is read: 'savings' is reported separately,
-- and 'credit' is a card, where a negative balance is money owed rather
-- than an overdraft, so it subtracts from net worth and may go below zero.
-- household_id is here as well as on persons. It is redundant — an account's
-- household is its person's — but it is what makes "every account in this
-- household" a filter rather than a join, and accounts never move between
-- households, so the two cannot drift. Transactions and subscriptions are
-- reached through their account instead of repeating it again.
CREATE TABLE IF NOT EXISTS accounts (
  id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  household_id    integer NOT NULL REFERENCES households(id) ON DELETE CASCADE,
  person_id       integer NOT NULL REFERENCES persons(id),
  name            text NOT NULL,
  currency        text NOT NULL DEFAULT 'AED',
  type            text NOT NULL DEFAULT 'current' CHECK (type IN ('current','savings','credit')),
  opening_balance double precision NOT NULL DEFAULT 0,
  is_active       smallint NOT NULL DEFAULT 1,
  sort_order      integer NOT NULL DEFAULT 0,
  created_at      timestamptz NOT NULL DEFAULT now()
);

-- Single ledger for every movement of money. `amount` is always positive;
-- `kind` carries the direction. A transfer is two rows sharing a transfer_id
-- (one transfer_out, one transfer_in), which lets the two legs hold different
-- amounts when the accounts are in different currencies.
CREATE TABLE IF NOT EXISTS transactions (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id  integer NOT NULL REFERENCES accounts(id),
  month       text NOT NULL,
  kind        text NOT NULL CHECK (kind IN ('income','expense','transfer_in','transfer_out')),
  amount      double precision NOT NULL,
  category    text,
  description text,
  transfer_id text,
  entry_date  text,
  -- Who recorded it. Nullable because rows written before this existed have no
  -- author, and inventing one would be worse than admitting it. ON DELETE SET
  -- NULL so removing a login never removes anyone's money.
  created_by  integer REFERENCES users(id) ON DELETE SET NULL,
  created_at  timestamptz NOT NULL DEFAULT now()
);

-- Recurring money, in both directions: subscriptions going out, salary coming
-- in. These are NOT written into `transactions`; they are applied on the fly
-- for every month in range, so editing or ending one immediately corrects past
-- and future months alike. Change the amount and it applies from that month on;
-- a one-off difference is an ordinary entry on top.
CREATE TABLE IF NOT EXISTS subscriptions (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id    integer NOT NULL REFERENCES accounts(id),
  name          text NOT NULL,
  direction     text NOT NULL DEFAULT 'expense' CHECK (direction IN ('expense','income')),
  amount        double precision NOT NULL,
  cycle         text NOT NULL DEFAULT 'monthly' CHECK (cycle IN ('monthly','yearly')),
  billing_month integer,
  start_month   text NOT NULL,
  end_month     text,
  category      text,
  notes         text,
  is_active     smallint NOT NULL DEFAULT 1,
  created_at    timestamptz NOT NULL DEFAULT now()
);

-- fetched_at stays text: it holds an ISO string and is compared by its date
-- prefix to decide whether today's rate has already been fetched.
CREATE TABLE IF NOT EXISTS exchange_rates (
  base_currency   text NOT NULL,
  target_currency text NOT NULL,
  rate            double precision NOT NULL,
  fetched_at      text NOT NULL,
  PRIMARY KEY (base_currency, target_currency)
);

-- What a currency was worth in a given month, so a past month stops moving.
-- Converting every month at today's rate means last March's total changes every
-- time the rupee does, and a net worth chart that rewrites its own history is
-- worse than no chart. The current month still uses the live rate — it is still
-- happening — and this row is refreshed while it is; when the month ends,
-- whatever was last written becomes the record.
--
-- Scoped per household because the primary currency and any manual rate
-- override are: one household's idea of the PKR rate is not another's. The
-- exchange_rates cache above stays shared, because a published rate is a fact
-- about the world rather than about anyone's budget.
CREATE TABLE IF NOT EXISTS exchange_rate_history (
  household_id    integer NOT NULL REFERENCES households(id) ON DELETE CASCADE,
  month           text NOT NULL,
  base_currency   text NOT NULL,
  target_currency text NOT NULL,
  rate            double precision NOT NULL,
  captured_at     timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (household_id, month, base_currency, target_currency)
);

-- Statements somebody chose to keep, and the rows read out of them.
--
-- This is a separate world from the ledger on purpose. Nothing here references
-- `transactions` and nothing in `transactions` references this: a statement is
-- a document a bank printed, and the ledger is what the household decided to
-- record. They disagree constantly — a statement holds the card payments the
-- ledger calls a transfer, and the ledger holds cash the statement never saw —
-- and joining them would force an answer to a question nobody asked yet.
--
-- Kept only when asked for. A scan that is read and closed still writes
-- nothing at all, which is what the scanner has always promised; this table
-- holds the ones somebody pressed a button to keep, so there is something for
-- next month to be compared against.
CREATE TABLE IF NOT EXISTS statements (
  id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  household_id    integer NOT NULL REFERENCES households(id) ON DELETE CASCADE,
  -- Which card or account this was printed for. SET NULL rather than CASCADE:
  -- closing an account in the ledger is a decision about the books, and it is
  -- no reason to destroy a document that was true when it was printed. The
  -- statement survives it, unattached.
  account_id      integer REFERENCES accounts(id) ON DELETE SET NULL,
  -- The period the statement covers, as the bank printed it. Not a month: card
  -- statements straddle two of them, and rounding a 15 Aug — 14 Sep period to
  -- "September" would be inventing a fact to make the sorting easier. Kept as
  -- dates, ordered by dates, and named in the client from these two.
  --
  -- NOT NULL even though a bank may print neither: a plain transaction list
  -- with no period gets the span of its own rows, worked out when it is kept.
  -- A statement with no period at all could not be placed in a sequence, which
  -- is the one thing this table exists to allow.
  period_start    text NOT NULL,
  period_end      text NOT NULL,
  currency        text,
  -- The bank's own figures, carried over from the scan so a kept statement can
  -- still be reconciled later without the document in front of you. Null
  -- wherever the statement printed none.
  opening_balance double precision,
  closing_balance double precision,
  kept_by         integer REFERENCES users(id) ON DELETE SET NULL,
  kept_at         timestamptz NOT NULL DEFAULT now()
);

-- There is deliberately no unique index over (household, account, period).
-- Re-keeping the same period replaces the old one, and that is done in the
-- route inside a transaction, where `account_id IS NOT DISTINCT FROM` can
-- match a null account the way a unique index cannot. A unique index over
-- COALESCE(account_id, 0) would express the rule, but it would also make
-- deleting a second account fail outright: ON DELETE SET NULL would collide
-- two surviving statements onto the same key. The rule is worth less than
-- being unable to close an account.
CREATE TABLE IF NOT EXISTS statement_rows (
  statement_id integer NOT NULL REFERENCES statements(id) ON DELETE CASCADE,
  -- The order the line appeared in the document. A statement is read in
  -- slices and reassembled, so without this the rows would come back in
  -- whatever order the database found them.
  sort_order   integer NOT NULL,
  -- `entry_date` rather than `date`: the transaction date, the day the thing
  -- happened, matching what the ledger calls the same column. `post_date` is
  -- when the bank settled it, null when the statement prints one date column.
  entry_date   text NOT NULL,
  post_date    text,
  -- The line exactly as the bank printed it. This is what makes a tidied
  -- merchant name checkable months later, so it is stored verbatim and never
  -- cleaned — the same rule the scanner reads under.
  raw          text NOT NULL,
  merchant     text NOT NULL,
  what         text,
  amount       double precision NOT NULL,
  direction    text NOT NULL CHECK (direction IN ('in','out')),
  kind         text NOT NULL,
  category     text NOT NULL,
  -- Carried over so a low-confidence reading stays marked as one. A guess that
  -- silently becomes a fact on being stored is worse than not keeping it.
  confidence   text NOT NULL DEFAULT 'high',
  PRIMARY KEY (statement_id, sort_order)
);

CREATE INDEX IF NOT EXISTS idx_statements_household ON statements(household_id, period_start);
CREATE INDEX IF NOT EXISTS idx_sessions_user ON sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_household_members_user ON household_members(user_id);
CREATE INDEX IF NOT EXISTS idx_household_invites_household ON household_invites(household_id);
-- Indexes on persons.household_id and accounts.household_id are created in
-- migrations.js instead: on a database predating households those columns are
-- added there, and this file is applied before it.
CREATE INDEX IF NOT EXISTS idx_accounts_person ON accounts(person_id);
CREATE INDEX IF NOT EXISTS idx_transactions_account_month ON transactions(account_id, month);
CREATE INDEX IF NOT EXISTS idx_transactions_month ON transactions(month);
CREATE INDEX IF NOT EXISTS idx_transactions_transfer ON transactions(transfer_id);
CREATE INDEX IF NOT EXISTS idx_subscriptions_account ON subscriptions(account_id);
