-- PostgreSQL schema. Every statement is IF NOT EXISTS so this file can be
-- applied on every boot; see ensureSchema.js.
--
-- Two deliberate carry-overs from the SQLite version, kept because changing
-- them would ripple all the way into the React code for no gain:
--   * money is `double precision`, not `numeric`. numeric is the correct type
--     for money in general, but the driver returns it as a string, and every
--     total in this app is arithmetic in JavaScript.
--   * is_active is a 0/1 smallint rather than a boolean, because the client
--     already compares it against 1 in several places.

-- Who can sign in. Separate from `persons`: a person is whose money an account
-- holds, a user is someone who can open the app. They usually line up, but the
-- app never assumes it.
CREATE TABLE IF NOT EXISTS users (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username      text NOT NULL,
  -- Optional, and nothing sends to it today. It is stored so that adding
  -- self-service password reset later is a contained change rather than a
  -- retrofit through signup and settings.
  email         text,
  password_hash text NOT NULL,
  -- Whether this person's amounts stay hidden until a passkey says otherwise.
  -- On the account rather than the device, so it follows you between them; each
  -- member of a household answers for themselves.
  lock_amounts  boolean NOT NULL DEFAULT false,
  created_at    timestamptz NOT NULL DEFAULT now()
);

-- SQLite had COLLATE NOCASE on the column; Postgres spells the same idea as a
-- unique index over the lowered value. Queries match on lower(username) to suit.
CREATE UNIQUE INDEX IF NOT EXISTS idx_users_username_lower ON users (lower(username));
-- The index over email lives in migrations.js, not here. This file is applied
-- before migrations run, and CREATE TABLE IF NOT EXISTS does not add a column
-- to a table that already exists — so on any database that predates `email`,
-- indexing it here fails. The rule: an index belongs in migrations.js whenever
-- the column it covers was added by a migration.

-- The token is the credential — it's random and stored as-is, so there is no
-- signing secret to manage or leak. Deleting a row logs that session out.
CREATE TABLE IF NOT EXISTS sessions (
  token      text PRIMARY KEY,
  user_id    integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz NOT NULL
);

-- A household is one budget: its own people, accounts, ledger and settings.
-- Every user has at least one and may belong to several — their own, and any
-- they have been invited into. Nothing is shared between them.
CREATE TABLE IF NOT EXISTS households (
  id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- Who may open which household, and what they may do there.
--   owner    everything, including inviting people and deleting the household
--   editor   can record and change money
--   viewer   read-only
CREATE TABLE IF NOT EXISTS household_members (
  household_id integer NOT NULL REFERENCES households(id) ON DELETE CASCADE,
  user_id      integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  role         text NOT NULL DEFAULT 'editor' CHECK (role IN ('owner','editor','viewer')),
  created_at   timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (household_id, user_id)
);

-- An invitation is a random code handed over out of band. It carries the role
-- it will grant, so accepting one can never quietly give more access than the
-- owner intended, and it is single-use.
CREATE TABLE IF NOT EXISTS household_invites (
  code         text PRIMARY KEY,
  household_id integer NOT NULL REFERENCES households(id) ON DELETE CASCADE,
  role         text NOT NULL DEFAULT 'editor' CHECK (role IN ('owner','editor','viewer')),
  created_by   integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at   timestamptz NOT NULL DEFAULT now(),
  expires_at   timestamptz NOT NULL,
  accepted_by  integer REFERENCES users(id) ON DELETE SET NULL,
  accepted_at  timestamptz
);

-- Key/value settings, per household. Holds primary_currency, which every
-- balance in that household is converted into for its totals and charts.
CREATE TABLE IF NOT EXISTS settings (
  household_id integer NOT NULL REFERENCES households(id) ON DELETE CASCADE,
  key          text NOT NULL,
  value        text NOT NULL,
  PRIMARY KEY (household_id, key)
);

CREATE TABLE IF NOT EXISTS persons (
  id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  household_id integer NOT NULL REFERENCES households(id) ON DELETE CASCADE,
  name         text NOT NULL,
  created_at   timestamptz NOT NULL DEFAULT now()
);

-- Free-form accounts: any number per person, each in its own currency.
-- `type` drives how a balance is read: 'savings' is reported separately,
-- and 'credit' is a card, where a negative balance is money owed rather
-- than an overdraft, so it subtracts from net worth and may go below zero.
-- household_id is here as well as on persons. It is redundant — an account's
-- household is its person's — but it is what makes "every account in this
-- household" a filter rather than a join, and accounts never move between
-- households, so the two cannot drift. Transactions and subscriptions are
-- reached through their account instead of repeating it again.
CREATE TABLE IF NOT EXISTS accounts (
  id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  household_id    integer NOT NULL REFERENCES households(id) ON DELETE CASCADE,
  person_id       integer NOT NULL REFERENCES persons(id),
  name            text NOT NULL,
  currency        text NOT NULL DEFAULT 'AED',
  type            text NOT NULL DEFAULT 'current' CHECK (type IN ('current','savings','credit')),
  opening_balance double precision NOT NULL DEFAULT 0,
  is_active       smallint NOT NULL DEFAULT 1,
  sort_order      integer NOT NULL DEFAULT 0,
  created_at      timestamptz NOT NULL DEFAULT now()
);

-- Single ledger for every movement of money. `amount` is always positive;
-- `kind` carries the direction. A transfer is two rows sharing a transfer_id
-- (one transfer_out, one transfer_in), which lets the two legs hold different
-- amounts when the accounts are in different currencies.
CREATE TABLE IF NOT EXISTS transactions (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id  integer NOT NULL REFERENCES accounts(id),
  month       text NOT NULL,
  kind        text NOT NULL CHECK (kind IN ('income','expense','transfer_in','transfer_out')),
  amount      double precision NOT NULL,
  category    text,
  description text,
  transfer_id text,
  entry_date  text,
  -- Who recorded it. Nullable because rows written before this existed have no
  -- author, and inventing one would be worse than admitting it. ON DELETE SET
  -- NULL so removing a login never removes anyone's money.
  created_by  integer REFERENCES users(id) ON DELETE SET NULL,
  created_at  timestamptz NOT NULL DEFAULT now()
);

-- Recurring money, in both directions: subscriptions going out, salary coming
-- in. These are NOT written into `transactions`; they are applied on the fly
-- for every month in range, so editing or ending one immediately corrects past
-- and future months alike. Change the amount and it applies from that month on;
-- a one-off difference is an ordinary entry on top.
CREATE TABLE IF NOT EXISTS subscriptions (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id    integer NOT NULL REFERENCES accounts(id),
  name          text NOT NULL,
  direction     text NOT NULL DEFAULT 'expense' CHECK (direction IN ('expense','income')),
  amount        double precision NOT NULL,
  cycle         text NOT NULL DEFAULT 'monthly' CHECK (cycle IN ('monthly','yearly')),
  billing_month integer,
  start_month   text NOT NULL,
  end_month     text,
  category      text,
  notes         text,
  is_active     smallint NOT NULL DEFAULT 1,
  created_at    timestamptz NOT NULL DEFAULT now()
);

-- fetched_at stays text: it holds an ISO string and is compared by its date
-- prefix to decide whether today's rate has already been fetched.
CREATE TABLE IF NOT EXISTS exchange_rates (
  base_currency   text NOT NULL,
  target_currency text NOT NULL,
  rate            double precision NOT NULL,
  fetched_at      text NOT NULL,
  PRIMARY KEY (base_currency, target_currency)
);

-- What a currency was worth in a given month, so a past month stops moving.
-- Converting every month at today's rate means last March's total changes every
-- time the rupee does, and a net worth chart that rewrites its own history is
-- worse than no chart. The current month still uses the live rate — it is still
-- happening — and this row is refreshed while it is; when the month ends,
-- whatever was last written becomes the record.
--
-- Scoped per household because the primary currency and any manual rate
-- override are: one household's idea of the PKR rate is not another's. The
-- exchange_rates cache above stays shared, because a published rate is a fact
-- about the world rather than about anyone's budget.
CREATE TABLE IF NOT EXISTS exchange_rate_history (
  household_id    integer NOT NULL REFERENCES households(id) ON DELETE CASCADE,
  month           text NOT NULL,
  base_currency   text NOT NULL,
  target_currency text NOT NULL,
  rate            double precision NOT NULL,
  captured_at     timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (household_id, month, base_currency, target_currency)
);

CREATE INDEX IF NOT EXISTS idx_sessions_user ON sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_household_members_user ON household_members(user_id);
CREATE INDEX IF NOT EXISTS idx_household_invites_household ON household_invites(household_id);
-- Indexes on persons.household_id and accounts.household_id are created in
-- migrations.js instead: on a database predating households those columns are
-- added there, and this file is applied before it.
CREATE INDEX IF NOT EXISTS idx_accounts_person ON accounts(person_id);
CREATE INDEX IF NOT EXISTS idx_transactions_account_month ON transactions(account_id, month);
CREATE INDEX IF NOT EXISTS idx_transactions_month ON transactions(month);
CREATE INDEX IF NOT EXISTS idx_transactions_transfer ON transactions(transfer_id);
CREATE INDEX IF NOT EXISTS idx_subscriptions_account ON subscriptions(account_id);
